package com.bank.bian.reconciliation;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Reconciliation
 *
 * Business Area:      Operations and Execution
 * Business Domain:    Operations
 * Functional Pattern: Process
 * Asset Type:         Reconciliation Case
 * Control Record:     Reconciliation Case Procedure
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Reconciliation — BIAN Semantic API")
                .description("Service Domain 'Reconciliation' (Process pattern) "
                        + "operating on the 'Reconciliation Case Procedure' control record.")
                .version("0.1.0"));
    }
}
