apiVersion: v2
name: sd-reconciliation
description: "BIAN Service Domain: Reconciliation (Process pattern, Operations and Execution)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - process
annotations:
  bian/business-area: "Operations and Execution"
  bian/business-domain: "Operations"
  bian/asset-type: "Reconciliation Case"
  bian/control-record: "Reconciliation Case Procedure"
